### ISSUE TITLE
not a win32

### ISSUE THREAD

**Issue by DimastyK** [kajott/TrackMeister#3] opened 2024-02-29 16:21 UTC
wendoze said "wrong descriptor". Can you build correct please?
![2024-02-29,19_20_47](https://github.com/kajott/TrackMeister/assets/135803967/9d1248a2-f739-4c3b-a60c-1b325b54012d)

**Comment by kajott** [comment] 2024-02-29 16:27
No idea what's going wrong there, but your window decorations sure look a lot like an operating system that's four years out of support now. If not even the OS vendor supports it, I'm not going to do that either :)

Might this be a duplicate of #1?

**Comment by DimastyK** [comment] 2024-02-29 17:59
TrackMeister-v1.0.0-win32-x86.zip runs OK, but same issue with OpenGL. About OS - this is win7 32bit with Aero theme.

**Comment by kajott** [comment] 2024-02-29 20:44
OK, so this **is** a duplicate of #1.

Regarding the issue at hand ... well, what can I say?
- You're running an operating system that's four years past its extended support period. Even though this doesn't seem related to your specific issues right now, let me be clear about this: You can't expect new software to "just work" on your outdated OS, and you can't expect the developers to give support for the resulting problems either.
- You're running on a CPU that is either so old that it doesn't support x86_64, or you have so little RAM that you decided to install the 32-bit version of the OS. Again, this doesn't seem to be directly related to your specific issue, as the 32-bit build I created just for you two months ago does seem to run in principle, but: You can't expect new software to run on such an outdated system.
- Then there's the GPU and OpenGL issue. This one's at least partly my fault, because out of laziness, I expect OpenGL 3.3, which is supported by every GPU from 2010 on. If your GPU or its drivers are so old that this doesn't work, I must say once again: You can't expect new software to run on such an outdated GPU.

If you really want to run TrackMeister on this old system, my best suggestion would indeed be to run it on Linux, or try to use [Mesa for Windows](https://github.com/pal1000/mesa-dist-win) as an OpenGL compatibility layer. Performance might not be great either way though.

**Comment by kajott** [comment] 2024-03-24 21:16
duplicate of #1

**Closed by kajott** 2024-03-24 21:16 UTC
